#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by cordexesg.dmi.dk - 2015/01/12 16:04:58
# Search URL: http://cordexesg.dmi.dk/esg-search/wget/?query=hurs EUR-11 CLMcom day rcp45&query=huss EUR-11 CLMcom day rcp45&query=huss EUR-11 CLMcom day historical&query=sfcWind EUR-11 CLMcom day historical&query=sfcWind EUR-11 CLMcom day rcp45&query=clt EUR-11 CLMcom day rcp45&query=clt EUR-11 CLMcom day historical&query=rsds EUR-11 CLMcom day historical&query=rsds EUR-11 CLMcom day rcp45&query=rlds EUR-11 CLMcom day rcp45&query=rlds EUR-11 CLMcom day historical&query=rsus EUR-11 CLMcom day historical&query=rsus EUR-11 CLMcom day rcp45&query=rlus EUR-11 CLMcom day rcp45&query=rlus EUR-11 CLMcom day historical&query=mrros EUR-11 CLMcom day historical&query=mrros EUR-11 CLMcom day rcp45&query=mrro EUR-11 CLMcom day rcp45&query=mrro EUR-11 CLMcom day historical&query=uas EUR-11 CLMcom day historical&query=uas EUR-11 CLMcom day rcp45&shards=esgf-data.dkrz.de:8983/solr&dataset_id=cordex.output.EUR-11.CLMcom.CNRM-CERFACS-CNRM-CM5.rcp45.r1i1p1.CCLM4-8-17.v1.day.uas.v20140515|carbon.dkrz.de
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId='https://cordexesg.dmi.dk/esgf-idp/openid/blaken'
#search_url='http://cordexesg.dmi.dk/esg-search/wget/?query=hurs EUR-11 CLMcom day rcp45&query=huss EUR-11 CLMcom day rcp45&query=huss EUR-11 CLMcom day historical&query=sfcWind EUR-11 CLMcom day historical&query=sfcWind EUR-11 CLMcom day rcp45&query=clt EUR-11 CLMcom day rcp45&query=clt EUR-11 CLMcom day historical&query=rsds EUR-11 CLMcom day historical&query=rsds EUR-11 CLMcom day rcp45&query=rlds EUR-11 CLMcom day rcp45&query=rlds EUR-11 CLMcom day historical&query=rsus EUR-11 CLMcom day historical&query=rsus EUR-11 CLMcom day rcp45&query=rlus EUR-11 CLMcom day rcp45&query=rlus EUR-11 CLMcom day historical&query=mrros EUR-11 CLMcom day historical&query=mrros EUR-11 CLMcom day rcp45&query=mrro EUR-11 CLMcom day rcp45&query=mrro EUR-11 CLMcom day historical&query=uas EUR-11 CLMcom day historical&query=uas EUR-11 CLMcom day rcp45&shards=esgf-data.dkrz.de:8983/solr&dataset_id=cordex.output.EUR-11.CLMcom.CNRM-CERFACS-CNRM-CM5.rcp45.r1i1p1.CCLM4-8-17.v1.day.uas.v20140515|carbon.dkrz.de'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
